[theme]
base = "light"              # 👈 Force Light mode
primaryColor = "#4CAF50"    # Customize accent color
backgroundColor = "#FFFFFF"  # App background
secondaryBackgroundColor = "#F0F2F6"  # Containers, sidebar
textColor = "#000000"       # Default text
font = "sans serif"         # Options: "sans serif", "serif", "monospace"
